#!/usr/bin/env node

'use strict'

const twoFactor = require('node-2fa');
const qrcode = require('qrcode-terminal');

const otpSecret = twoFactor.generateSecret({name: 'Ceasium', account: 'Ikea Trådfri Rest API OTP'});

console.log(`OTP secret is: ${otpSecret.secret}`);
console.log(`Enter this into `);
console.log(`1. your OTP/2FA code generator (e.g. Google Authenticator)`);
console.log(`2. the OTP_SECRET environment variable (e.g. in the .env file)`);
console.log(`3. any user of the AP endpoints (e.g. an app etc)`)
console.log();

qrcode.generate(otpSecret.uri.replace('%3F', '?')); // replace '%3F' with a proper '?' to make the google app work..
